site_name: DIDComm.org
theme:
  name: material
  logo: didcomm-logo.png
  favicon: didcomm-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TelegramSam/didcomm.org

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/TelegramSam/didcomm.org"  target="_blank" rel="noopener">DIDComm.org</a>

nav:
  - Home: index.md
  - Protocols: protocols.md
  - Action Menu:
    - 1.0: action-menu/1.0/readme.md
    - 2.0: action-menu/2.0/readme.md
  - Basic Message:
    - 1.0: basicmessage/1.0/readme.md
    - 2.0: basicmessage/2.0/readme.md
  - Coordinate Mediation:
    - 1.0: coordinate-mediation/1.0/readme.md
    - 2.0: coordinate-mediation/2.0/readme.md
    - 3.0: coordinate-mediation/3.0/readme.md
  - Data Agreement Context Decorator:
    - 1.0: data-agreement-context-decorator/1.0/readme.md
  - Data Agreement Negotiation:
    - 1.0: data-agreement-negotiation/1.0/readme.md
  - Data Agreement Proofs:
    - 1.0: data-agreement-proofs/1.0/readme.md
  - Data Agreement Termination:
    - 1.0: data-agreement-termination/1.0/readme.md
  - Data Disclosure Agreement:
    - 1.0: data-disclosure-agreement/1.0/readme.md
  - Discover Features:
    - 1.0: discover-features/1.0/readme.md
    - 2.0: discover-features/2.0/readme.md
  - Issue Credential:
    - 1.1: issue-credential/1.1/readme.md
    - 2.0: issue-credential/2.0/readme.md
    - 3.0: issue-credential/3.0/readme.md
  - Media Sharing:
    - 1.0: media-sharing/1.0/readme.md
  - Message Pickup:
    - 1.0: messagepickup/1.0/readme.md
    - 2.0: messagepickup/2.0/readme.md
    - 3.0: messagepickup/3.0/readme.md
  - Out of Band:
    - 2.0: out-of-band/2.0/readme.md
  - Present Proof:
    - 1.0: present-proof/1.0/readme.md
    - 2.0: present-proof/2.0/readme.md
    - 3.0: present-proof/3.0/readme.md
  - Question Answer:
    - 1.0: question-answer/1.0/readme.md
  - Receipts:
    - 1.0: receipts/1.0/readme.md
  - Report Problem:
    - 2.0: report-problem/2.0/readme.md
  - Routing:
    - 2.0: routing/2.0/readme.md
  - Shorten URL:
    - 1.0: shorten-url/1.0/readme.md
  - Trust Ping:
    - 2.0: trust-ping/2.0/readme.md
  - User Profile:
    - 1.0: user-profile/1.0/readme.md
  - Maintainer Guide: maintainer-guide.md
  - PR Guide: pr-guide.md
  - Protocol Example: protocol-example.md