site_name: DIDComm.org
theme:
  name: material
  logo: didcomm-logo.png
  favicon: didcomm-logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TelegramSam/didcomm.org

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/TelegramSam/didcomm.org"  target="_blank" rel="noopener">DIDComm.org</a>

nav:
  - Home: index.md
  - Protocols:
    - protocols/index.md
    - Action Menu:
      - protocols/action-menu/1.0/readme.md
      - protocols/action-menu/2.0/readme.md
    - Basic Message:
      - protocols/basicmessage/1.0/readme.md
      - protocols/basicmessage/2.0/readme.md
    - Coordinate Mediation:
      - protocols/coordinate-mediation/1.0/readme.md
      - protocols/coordinate-mediation/2.0/readme.md
      - protocols/coordinate-mediation/3.0/readme.md
    - Data Agreement Context Decorator:
      - protocols/data-agreement-context-decorator/1.0/readme.md
    - Data Agreement Negotiation:
      - protocols/data-agreement-negotiation/1.0/readme.md
    - Data Agreement Proofs:
      - protocols/data-agreement-proofs/1.0/readme.md
    - Data Agreement Termination:
      - protocols/data-agreement-termination/1.0/readme.md
    - Data Disclosure Agreement:
      - protocols/data-disclosure-agreement/1.0/readme.md
    - Discover Features:
      - protocols/discover-features/1.0/readme.md
      - protocols/discover-features/2.0/readme.md
    - Issue Credential:
      - protocols/issue-credential/1.1/readme.md
      - protocols/issue-credential/2.0/readme.md
      - protocols/issue-credential/3.0/readme.md
    - Media Sharing:
      - protocols/media-sharing/1.0/readme.md
    - Message Pickup:
      - protocols/messagepickup/1.0/readme.md
      - protocols/messagepickup/2.0/readme.md
      - protocols/messagepickup/3.0/readme.md
    - Out of Band:
      - protocols/out-of-band/2.0/readme.md
    - Present Proof:
      - protocols/present-proof/1.0/readme.md
      - protocols/present-proof/2.0/readme.md
      - protocols/present-proof/3.0/readme.md
    - Question Answer:
      - protocols/question-answer/1.0/readme.md
    - Receipts:
      - protocols/receipts/1.0/readme.md
    - Report Problem:
      - protocols/report-problem/2.0/readme.md
    - Routing:
      - protocols/routing/2.0/readme.md
    - Shorten URL:
      - protocols/shorten-url/1.0/readme.md
    - Trust Ping:
      - protocols/trust-ping/2.0/readme.md
    - User Profile:
      - protocols/user-profile/1.0/readme.md
  - Maintainer Guide: maintainer-guide.md
  - PR Guide: pr-guide.md
  - Protocol Example: protocol-example.md